title: "Yousef's Notes"
baseURL: "https://notes.yousef.gg"
theme:
  - algorithmica
  - reveal-hugo
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
outputs:
  home:
    - HTML
    - SearchIndex
markup:
  goldmark:
    footnote: false # katex conflict
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 4
    wrapperClass: highlight
sectionPagesMenu: main
params:
  repo: "https://github.com/yamirghofran/university-notes"
  description: "Yousef Amirghofran's Notes from BCSAI classes at IE University and beyond."
  keywords: "computer science, algorithms, data structures, computer architecture, programming"
  author: "Yousef Amirghofran"
  image: "/img/og-image.png"
  reveal_hugo:
    #theme: white
    slide_number: true
    transition: none
    custom_theme: "slides.sass"
    custom_theme_compile: true
