baseURL: "https://yourdomain.com"
theme:
  - algorithmica
  - reveal-hugo
pygmentsUseClasses: true
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
outputs:
  home:
    - HTML
    - SearchIndex
markup:
  goldmark:
    footnote: false # katex conflict
    renderer:
      unsafe: true
title: "Algorithmica"
sectionPagesMenu: main
params:
  repo: "https://github.com/yamirghofran/university-notes"
  reveal_hugo:
    #theme: white
    slide_number: true
    transition: none
    custom_theme: "slides.sass"
    custom_theme_compile: true
